import { categoryDemoData } from '@/features/category/constants/demoData'
import type { Post } from '../types/Post'

export const postDemoData: Post[] = [
  {
    id: 1,
    title: 'Post 1',
    description: 'Description 1',
    path: 'post-1',
    content: 'Content 1',
    statusId: 1,
    status: '下書き',
    thumbnailId: 1,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　花子',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 1',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[0], categoryDemoData[1]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    title: 'Post 2',
    description: 'Description 2',
    path: 'post-2',
    content: 'Content 2',
    statusId: 3,
    status: '公開中',
    thumbnailId: 2,
    isDisplayThumbnail: true,
    updatedTenantUserId: 1,
    updatedTenantUserName: '山田　太郎',
    authorTenantUserId: 1,
    authorTenantUserName: 'Author 2',
    tenantId: 1,
    tenantName: 'Tenant 1',
    categories: [categoryDemoData[2]],
    publishedAt: '2021-10-01',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  }
]
