import type { Category } from '../types/Post'

export const categoryDemoData: Category[] = [
  {
    id: 1,
    name: 'Category 1',
    description: 'Description 1',
    isActivated: true,
    parentId: 0,
    slug: 'category-1',
    sortOrder: 1,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 2,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: false,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  },
  {
    id: 3,
    name: 'Category 2',
    description: 'Description 2',
    isActivated: true,
    parentId: 0,
    slug: 'category-2',
    sortOrder: 2,
    tenantId: 1,
    updatedTenantUserId: 1,
    updatedTenantUserName: 'User 1',
    tenantName: 'Tenant 1',
    createdAt: '2021-10-01',
    updatedAt: '2021-10-01'
  }
]
